[package]
name = "blank"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.15.0", directory="yarn-project/aztec-nr/aztec" }
